dcsaorg/DCSA-API-Validator

- src/test/java/org/dcsa/api_validator/ovs/v1/schedules/RestAssuredSimpleTest.java
- src/test/java/org/dcsa/api_validator/ovs/v1/schedules/ScheduleSubscriptionsTest.java
- src/test/java/org/dcsa/api_validator/ovs/v1/transportcalls/GetTransportCallsTest.java
- src/test/java/org/dcsa/api_validator/ovs/v1/transportcalls/TransportCallSubscriptionsTest.java
- src/test/resources/ovs/v1/ScheduleSubscriptionSchema.json
- src/test/resources/ovs/v1/ScheduleSubscriptionsSchema.json
- src/test/resources/ovs/v1/TransportCallSchema.json
- src/test/resources/ovs/v1/TransportCallSubscription.json
- src/test/resources/ovs/v1/TransportCallSubscriptionsSchema.json
- src/test/resources/ovs/v1/TransportCallsSchema.json
Cleanup
Change date-range input to match regex: ^(P(\\dY)?(\\dM)?(\\dD)?)?(T(\\dH)?(\\dM)?(\\dS)?)?$
vesselIMONumber changed from Integer -> String
> Multiple changes

- .github/workflows/validateEBLMaster.yml
- .github/workflows/validateTntV1.yml
- EBLV1.xml
- pom.xml
- src/test/java/org/dcsa/api_validator/ebl/v1/shippinginstructions/PostShippingInstructionsTest.java
- src/test/java/org/dcsa/api_validator/ebl/v1/shippinginstructions/RestAssuredSimpleTest.java
- src/test/java/org/dcsa/api_validator/ebl/v1/transportDocuments/RestAssuredSimpleTest.java
- src/test/resources/ebl/v1/ShippingInstructionsSchema.json
Add eBL test workflow
Add some initial tests
> Initial eBL tests

- .github/workflows/validateEBLMaster.yml
- .github/workflows/validateOVSMaster.yml
- .github/workflows/validateTnTMaster.yml
- .github/workflows/validateTntV1.yml
- src/test/java/org/dcsa/api_validator/conf/Configuration.java
- src/test/java/org/dcsa/api_validator/tnt/v1/EventSubscriptionsTest.java
- src/test/java/org/dcsa/api_validator/tnt/v2/EventSubscriptionsTest.java
The existing data needs to be removed in the TNT repos, and the new parameter should be added as well
> Add configurable callback URI for TNT

- src/test/java/org/dcsa/api_validator/ebl/v1/shippinginstructions/PostShippingInstructionsTest.java
> EBL: Use a valid HSCode

- src/test/java/org/dcsa/api_validator/ebl/v1/shippinginstructions/PostShippingInstructionsTest.java
> Fix bugs in test data

- src/test/java/org/dcsa/api_validator/TestUtil.java
- src/test/java/org/dcsa/api_validator/ebl/v1/shippinginstructions/PostShippingInstructionsTest.java
- src/test/resources/ebl/v1/shipping-instructions/basic-valid-shipping-instructions.json
> Simplify test data handling

- src/test/resources/ebl/v1/shipping-instructions/basic-valid-shipping-instructions.json
Fixes the test for the EBL update
> Update VolumeUnit from MTQ -> CBM

- src/test/resources/ebl/v1/shipping-instructions/basic-valid-shipping-instructions.json
To match https://github.com/dcsaorg/DCSA-EBL/pull/43
> Move carrierBookingReference to cargoItems

- src/test/java/org/dcsa/api_validator/ebl/v1/shippinginstructions/PostShippingInstructionsTest.java
- src/test/resources/ebl/v1/shipping-instructions/basic-valid-shipping-instructions.json
Goes with https://github.com/dcsaorg/DCSA-EBL/pull/49
> Test data update

- pom.xml
> Bump spring-boot to 2.4.2

- src/test/resources/ebl/v1/shipping-instructions/basic-valid-shipping-instructions.json
> Remove shipmentLocations from SI

- src/test/resources/ebl/v1/shipping-instructions/basic-valid-shipping-instructions.json
> Update test data to match IM changes

- .github/workflows/validateTnTMaster.yml
- src/test/java/org/dcsa/api_validator/ovs/v1/portcallevents/PostPortCallEventsTest.java
- src/test/java/org/dcsa/api_validator/ovs/v1/transportcalls/PostTransportCallsTest.java
- src/test/java/org/dcsa/api_validator/ovs/v1/transportcalls/TransportCallSubscriptionsTest.java
- src/test/java/org/dcsa/api_validator/tnt/v2/GetEventsTest.java
- src/test/resources/ovs/v1/TransportEvent.json
- src/test/resources/ovs/v1/TransportEvents.json
> Add trivial test cases to catch DCSA-TNT#27

- src/test/resources/ebl/v1/shipping-instructions/basic-valid-shipping-instructions.json
To match https://github.com/dcsaorg/DCSA-Information-Model/pull/38 + https://github.com/dcsaorg/DCSA-EBL/pull/76
> Remove isPartLoad from SI

- src/test/resources/ebl/v1/shipping-instructions/basic-valid-shipping-instructions.json
> Re-add Address on party in SI

- src/test/resources/ebl/v1/shipping-instructions/basic-valid-shipping-instructions.json
> Add displayedAddress + partyContactDetails in test SI

- src/test/resources/ebl/v1/shipping-instructions/basic-valid-shipping-instructions.json
> Add transportDocumentType to SI

- src/test/java/org/dcsa/api_validator/ebl/v1/shippinginstructions/ShippingInstructionsTest.java
- src/test/resources/ebl/v1/shipping-instructions/basic-valid-shipping-instructions.json
> Add isChargesDisplayed to basic SI

- src/test/java/org/dcsa/api_validator/tnt/v2/EventSubscriptionsTest.java
> TNT: Test deletion of subscription

- .github/workflows/validateEBLMaster.yml
- .github/workflows/validateOVSMaster.yml
- .github/workflows/validateTnTMaster.yml
- dcsa-api-validator.iml
> CI: Set CALLBACK_URI during tests

- .github/workflows/validateTntV1.yml
- .github/workflows/validateTntV1X.yml
- src/test/java/org/dcsa/api_validator/tnt/v1/GetEventsIDTest.java
- src/test/java/org/dcsa/api_validator/tnt/v1/GetEventsTest.java
> Expand on TNT1.2 test coverage

- .github/workflows/validateEBLMaster.yml
- src/test/java/org/dcsa/api_validator/tnt/v1/EventSubscriptionsTest.java
- src/test/java/org/dcsa/api_validator/tnt/v2/EventSubscriptionsTest.java
> Add basic TNT CRUD tests

- .github/workflows/validateEBLMaster.yml
- .github/workflows/validateTnTMaster.yml
- src/test/java/org/dcsa/api_validator/tnt/v2/EventSubscriptionsTest.java
- src/test/java/org/dcsa/api_validator/tnt/v2/GetEventsIDTest.java
- src/test/java/org/dcsa/api_validator/tnt/v2/GetEventsTest.java
- src/test/resources/tnt/v2/EventSchema.json
- src/test/resources/tnt/v2/EventsSchema.json
- src/test/resources/tnt/v2/TransportEventSchema.json
- src/test/resources/tnt/v2/TransportEventsSchema.json
> Update to reflect recent changes

- .github/workflows/validateEBLMaster.yml
- .github/workflows/validateTnTMaster.yml
> CI: Reset branches to master

- src/test/resources/ebl/v1/shipping-instructions/basic-valid-shipping-instructions.json
> Remove usage of locationID in eBL

- src/test/java/org/dcsa/api_validator/tnt/v2/GetEventsTest.java
- Added testing for sort attribute
- Refactoring code
- ensure json schema is respected at all stages
> Improvements to DDT-32

- src/test/resources/ovs/v1/ScheduleSubscriptionSchema.json
- src/test/resources/ovs/v1/ScheduleSubscriptionsSchema.json
- src/test/resources/ovs/v1/TransportCallSchema.json
- src/test/resources/ovs/v1/TransportCallSubscription.json
- src/test/resources/ovs/v1/TransportCallSubscriptionsSchema.json
> Correct vessel IMO number examples

- .github/workflows/validateTnTMaster.yml
- src/test/java/org/dcsa/api_validator/tnt/v2/GetEventsTest.java
Resolves:
https://dcsa.atlassian.net/browse/DDT-168
> Enabled all TNT test

- src/test/resources/ovs/v2/EventSchema.json
- src/test/resources/ovs/v2/EventsSchema.json
> Correct JSON Schema's for OVS API validator

- src/test/resources/ovs/v2/EventSchema.json
- src/test/resources/ovs/v2/EventsSchema.json
- src/test/resources/ovs/v2/ovsTimeStamps/TimeStampsSample.json
Fix for https://github.com/dcsaorg/DCSA-OVS/pull/45
> Fixed sample schema for timestamp call.

- .github/workflows/validateOVSMaster.yml
- src/test/resources/ovs/v2/EventSchema.json
- src/test/resources/ovs/v2/EventsSchema.json
> Correct OVS EventsSchema.json

- src/test/java/org/dcsa/api_validator/ovs/v2/PostTimestampsTest.java
> Enable remaining test

- src/test/java/org/dcsa/api_validator/jit/v1/PostTimestampsTest.java
-1st:  post timestamp with mandatory + TransportCallSequenceNumber
- 2nd: post timestamp to show error is returned when timestamp ambiguous.
> DDT-341-Testcase that covers TransportCallSequenceNumber

- .github/workflows/validateJITMaster.yml
> Finish the OVS -> JIT rename

- src/test/java/org/dcsa/api_validator/jit/v1/GetEventsTest.java
- src/test/resources/jit/v1/EventsSchema.json
Transport events have been removed from JIT
> Update API validator tests for JIT

- src/test/java/org/dcsa/api_validator/bkg/v1/BookingTestConfiguration.java
- src/test/java/org/dcsa/api_validator/bkg/v1/bookings/GetBookingTest.java
> DDT-485 Get booking with carrierbookingrequestreference test

- src/test/java/org/dcsa/api_validator/tnt/v2/EventSubscriptionsTest.java
https://dcsa.atlassian.net/browse/DDT-717
> Disabled test due to being incompatible with the new core changes.

- src/test/java/org/dcsa/api_validator/jit/v1/GetEventsTest.java
> DDT-706: Fix limit test

- BKGV1.xml
- src/test/java/org/dcsa/api_validator/bkg/v1/BookingTestConfiguration.java
- src/test/java/org/dcsa/api_validator/bkg/v1/cancellations/CancelBookingTest.java
> DDT-489 add booking cancellation tests
